apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: ${project}
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: ${region}
          # name of the GKE cluster
          clusterName: ${project}-gke
          clusterProjectID: ${project}
          # reference the sa from above
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
